version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app-backend
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chat-app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: chat-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: