apiVersion: v1
kind: Service
metadata:
  name: real-time-chat-app-backend
  namespace: default
  labels:
    app: real-time-chat-app-backend
spec:
  selector:
    app: real-time-chat-app-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP